### ISSUE TITLE
Top navigation menu RWD issues

### ISSUE THREAD

**Issue by adam-maciejewski** [jhejlik/Mageek_OpenmageTheme#2]
There is a problem with top navigation menu on RWD views. For example desktop view (where everything works fine):

![obraz](https://user-images.githubusercontent.com/66788708/97298536-d6cc5680-1853-11eb-8ec4-757fdb424894.png)

For 1240px there is no access to last top menu position `System`. It is hide under searchbar:

![obraz](https://user-images.githubusercontent.com/66788708/97298712-214dd300-1854-11eb-9421-8a9a471d5a88.png)

On smallest resolutions another top menu positions are not available (768px as example):

![obraz](https://user-images.githubusercontent.com/66788708/97298933-738ef400-1854-11eb-82e3-4987a139852b.png)

**Comment by jhejlik** [comment]
Hi, the theme is desktop only (just like the default theme). The minimum usable screen resolution is 1280px. If you have many other menu items, they are hidden under the search. I know it's a problem.
A quick fix is to edit custom.css

Find **.header-right fieldset input.input-text** and set:
` width: 120px; min-width: 120px;`

I will provide the fix in the next version.
